// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f3f10c03-e21f-485c-8281-1f4e6d3f1bcb",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_tzs8UPVgn",
    "aws_user_pools_web_client_id": "57kdlvhnisck0383v4mh4u4g07",
    "oauth": {}
};


export default awsmobile;
